### PR TITLE
 #134-Create-new-home-design

### LINKED ISSUE #134: Create new home design
### Objective
Create a few prototypes for displaying the courses on the home screen that are more aligned to the current tumlive view and less reliant on a thumb nail, code the best one in our flutter project. 

### Progress: 
- [x] sketches created
- [x] code written
#### More specific: 
- [x] fix livenow for courses
- [x] livestreams redirect to video player
- [x] display viwercount
- [x] display roomname, redirect to navigaTUM
- [x] display last lecture
- [x] add pulsing LiveNow as on tumlive
- [x] display colored stirp based on fachschaft (eg. blue for **IN**0009)
- [x] make compatible with darkmode
- [x] make listview compatible with new cards
- [x] clean up code of new components
- [x] make compatible with table view
- [x] add null- and exception checks for edge cases (eg. for extra long titles, unset fields) 
- [x] add navigation to course detail view
- [ ] incorporate Benedicts feedback

### Impediment: 
course.streams is somehow always empty

### TumLive view: 
Screenshot 2024-01-04 at 17 11 40

### Home: 
Screenshot 2024-01-14 at 16 59 13

Screenshot 2024-01-14 at 16 59 13

#### Course Detail View: 
Screenshot 2024-01-21 at 17 47 59

Screenshot 2024-01-21 at 17 48 39

### PR DESCRIPTION
**Pull request by milenark**
Closes #134.

### CODE REVIEW

**Comment by GravityDarkLab** [comment]
Is this still a Draft or ready for Review ?

File: lib/views/course_view/components/course_card.dart [hunk 1]
```diff
@@ -1,144 +1,397 @@
...
+                child: Column(
+                  crossAxisAlignment: CrossAxisAlignment.start,
                   children: [
+                    const SizedBox(height: 10),
+                    _buildCourseTitle(themeData.textTheme),
                     _buildCourseSubtitle(themeData.textTheme),
-                    _buildCourseIsLive(),
+                    const SizedBox(height: 15),
+                    _buildLocation(),
+                    //_buildCourseIsLive(),
```
Comment (ahmetsenturk) [inline lib/views/course_view/components/course_card.dart:133]: Pls remove the commented-out codes :)

File: lib/views/course_view/components/course_card.dart [hunk 2]
```diff
@@ -1,144 +1,397 @@
...
     );
   }
 
   Widget _buildCourseImage() {
+    if (path == null) return const SizedBox();
     return Stack(
       children: [
         AspectRatio(
-          aspectRatio: 10 / 7,
+          aspectRatio: 16 / 12, //TODO how are the thumbnails given?
```
Comment (ahmetsenturk) [inline lib/views/course_view/components/course_card.dart:186]: Are you referring to the thumbnail ratio here? Did you find it?

File: lib/views/course_view/components/course_card.dart [hunk 3]
```diff
@@ -1,144 +1,397 @@
...
+              path!,
               fit: BoxFit.cover,
             ),
           ),
         ),
+        /*Positioned(
+          bottom: 3, // Adjust this value based on your layout
+          right: 3, // Adjust this value based on your layout
+          child: _buildCourseViewerCount(),
+        ),*/
```
Comment (ahmetsenturk) [inline lib/views/course_view/components/course_card.dart:199]: Remove if it's not going to be used, or use 🙃

File: lib/views/course_view/components/course_card.dart [hunk 4]
```diff
@@ -1,144 +1,397 @@
...
   }
 
+  Widget _buildLocation() {
+    if (roomName == null) return const SizedBox();
+
+    final Uri url = roomName != null
+        ? Uri.parse('https://nav.tum.de/room/$roomNumber')
+        : Uri.parse(
+            'https://nav.tum.de/room/',
+          ); //will give an error on NavigaTUM
```
Comment (ahmetsenturk) [inline lib/views/course_view/components/course_card.dart:211]: What does this mean?

File: lib/views/course_view/components/course_card.dart [hunk 5]
```diff
@@ -1,144 +1,397 @@
...
+      ),
+    );
+  }
+
   Widget _buildCourseTitle(TextTheme textTheme) {
     return Text(
       title,
       overflow: TextOverflow.ellipsis,
-      maxLines: 3,
+      //maxLines: 2, //TODO check that this never causes overflow
```
Comment (ahmetsenturk) [inline lib/views/course_view/components/course_card.dart:255]: I am not sure if I understood it correctly, but if you are referring to title text overflow, then maybe you can use sth. like this? https://stackoverflow.com/questions/44579918/flutter-wrap-text-on-overflow-like-insert-ellipsis-or-fade

**Review by ahmetsenturk — CHANGES_REQUESTED** [review]
Very good job, Milena!
- Please resolve the merge conflicts
- Remove the commented-out code snippets
- Solve all the TODOs you left; if you cannot basically because it is out of scope or for some other reason - then create new tasks out of those TODOs 😊

**Comment by Anishyou** [comment]
Overall, it looks good. Great Work 👍  . Since we have had quite new changes in dev. I would suggest you update it and solve merge conflicts. Then we can do some more testing.

File: lib/views/course_view/components/course_card.dart (hunk 4 above)
Comment (milenark) [reply lib/views/course_view/components/course_card.dart:211]: The idea was that when the roomnumber is not is not set for a course, we still redirect to NavigaTum with the invalid room number and make them return an "invalid" 

But I will change it so that the section is simply not being displayed in that case

**Comment by cbetul** [comment]
I tried to test on landscape mode especially and it looks great!! good work Milena
Only one thing, there is a bug I guess cause when I try to pin a course, it doesn't show up on the pinned section.

https://github.com/TUM-Dev/gocast_mobile/assets/43902289/c040d31e-0cc6-4cc4-8778-09075c37f493

**Comment by milenark** [comment]
> I tried to test on landscape mode especially and it looks great!! good work Milena Only one thing, there is a bug I guess cause when I try to pin a course, it doesn't show up on the pinned section.
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-01-26.at.00.11.12.mp4

Yes I found that too - I can take a look at it, but I tried it on dev and it is a problem there too, so nothing to do with my code I think

**Comment by GravityDarkLab** [comment]
> I tried to test on landscape mode especially and it looks great!! good work Milena Only one thing, there is a bug I guess cause when I try to pin a course, it doesn't show up on the pinned section.
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-01-26.at.00.11.12.mp4

Just change the filter to all or WS22 :)

**Comment by cbetul** [comment]
> > I tried to test on landscape mode especially and it looks great!! good work Milena Only one thing, there is a bug I guess cause when I try to pin a course, it doesn't show up on the pinned section.
> > Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-01-26.at.00.11.12.mp4
> 
> Yes I found that too - I can take a look at it, but I tried it on dev and it is a problem there too, so nothing to do with my code I think

i can take a look at it

**Comment by GravityDarkLab** [comment]
> > I tried to test on landscape mode especially and it looks great!! good work Milena Only one thing, there is a bug I guess cause when I try to pin a course, it doesn't show up on the pinned section.
> > Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-01-26.at.00.11.12.mp4
> 
> Yes I found that too - I can take a look at it, but I tried it on dev and it is a problem there too, so nothing to do with my code I think

This is not a problem @milenark & @cbetul , if you change the filter parameter you ll find them.
the Filter parameter is set to the latest semester always (latest for the server is ws23).

**Review by ahmetsenturk — APPROVED** [review]
Great work guys 😊
